export * from "../../Pages/dashboard/home";
export * from "../../Pages/dashboard/profile";
export * from "../../Pages/dashboard/tables";
export * from "../../Pages/dashboard/notifications";
export * from "../../Pages/dashboard/addparticipants";
export * from "../../Pages/dashboard/addcohort";
export * from "../../Pages/dashboard/addactivity";
export * from "../../Pages/dashboard/activitylist";
export * from "../../Pages/dashboard/participantlist";
export * from "../../Pages/dashboard/cohortlist";
export * from "../../Pages/dashboard/domainlist";
export * from "../../Pages/dashboard/editdomain"
export * from "../../Pages/dashboard/addsession";
export * from "../../Pages/dashboard/sessionlist";
export * from "../../Pages/dashboard/addevaluation";
export * from "../../Pages/dashboard/evaluationlist";
export * from "../../Pages/dashboard/adddomain";
export * from "../../Pages/dashboard/cohortreport";
export * from "../../Pages/dashboard/cohortreportdetails";
export * from "../../Pages/dashboard/oxfordHappiness";
export * from "../../Pages/dashboard/caspQuestions";
export * from "../../Pages/dashboard/participantReport";
export * from "../../Pages/dashboard/AdminList";
export * from "../../Pages/dashboard/moca";
export * from "../../Pages/dashboard/sessionAttendence";
export * from "../../Pages/dashboard/oxfordlist";
export * from "../../Pages/dashboard/mocalist";
export * from "../../Pages/dashboard/casplist";

