export const GET_PARTICIPANTS_REQUEST = "GET_PARTICIPANTS_REQUEST";
export const GET_PARTICIPANTS_SUCCESS = "GET_PARTICIPANTS_SUCCESS";
export const GET_PARTICIPANTS_FAILURE = "GET_PARTICIPANTS_FAILURE";

export const GET_ADMIN_REQUEST = "GET_ADMIN_REQUEST";
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";
export const GET_ADMIN_FAILURE = "GET_ADMIN_FAILURE";

export const GET_COHORTS_REQUEST = "GET_COHORTS_REQUEST";
export const GET_COHORTS_SUCCESS = "GET_COHORTS_SUCCESS";
export const GET_COHORTS_FAILURE = "GET_COHORTS_FAILURE";

export const GET_ACTIVITIES_REQUEST = "GET_ACTIVITIES_REQUEST";
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS";
export const GET_ACTIVITIES_FAILURE = "GET_ACTIVITIES_FAILURE";

export const GET_DOMAINS_REQUEST = "GET_DOMAINS_REQUEST";
export const GET_DOMAINS_SUCCESS = "GET_DOMAINS_SUCCESS";
export const GET_DOMAINS_FAILURE = "GET_DOMAINS_FAILURE";

export const GET_EVALUATIONS_REQUEST = "GET_EVALUATIONS_REQUEST";
export const GET_EVALUATIONS_SUCCESS = "GET_EVALUATIONS_SUCCESS";
export const GET_EVALUATIONS_FAILURE = "GET_EVALUATIONS_FAILURE";

export const GET_SESSIONS_REQUEST = "GET_SESSIONS_REQUEST";
export const GET_SESSIONS_SUCCESS = "GET_SESSIONS_SUCCESS";
export const GET_SESSIONS_FAILURE = "GET_SESSIONS_FAILURE";
